# Use the latest LTS version of Node.js
FROM node:lts

# Copy the contents of the current directory into the /app directory in the container
COPY . /src

# Set the working directory in the container
WORKDIR /src

# Install Node.js dependencies
RUN npm install --legacy-peer-deps

# Set the environment to test
ENV NODE_ENV=test

# Expose the port your application will listen on
EXPOSE 3000

# Define the command to start your application
CMD ["npm", "run", "test"]
