# Use the latest LTS version of Node.js
FROM node:lts

# Set the working directory in the container
WORKDIR /src

# Copy package.json and package-lock.json to leverage Docker layer caching
COPY package*.json ./

# Install Node.js dependencies
RUN npm install --legacy-peer-deps

# Copy the rest of the application code
COPY . .

# Set the environment to development
ENV NODE_ENV=development

# Expose the port your application will listen on
EXPOSE 3000

# Define the command to start your application
CMD ["npm", "run", "dev"]
