version: '3.9'

services:
  proxy:
    container_name: proxy
    image: nginx:latest # Use the latest NGINX image
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    networks:
      - backend

  server:
    container_name: prod_server
    build:
      context: ./
      dockerfile: Dockerfile.prov
    ports:
      - '3000:3000'
    volumes:
      - ./:/app:delegated
      - /app/node_modules
    restart: unless-stopped
    networks:
      - backend

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - '3306:3306'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: payee_db
      MYSQL_USER: root
      MYSQL_PASSWORD: passwd
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  redis:
    image: redis:latest # Use the latest Redis image
    container_name: redis
    ports:
      - '6379:6379'
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
